services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 3306:3306
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: facebell
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data